const menu = [
  {
    name: "Espresso",
    category: "coffee_and_tea",
    price: 2.2,
    description: null,
    size: null,
    special: false,
  },
  {
    name: "Espresso dopio",
    category: "coffee_and_tea",
    price: 2.8,
    description: null,
    size: null,
    special: false,
  },
  {
    name: "Americano",
    category: "coffee_and_tea",
    price: 2.5,
    description: null,
    size: null,
    special: false,
  },
  {
    name: "Cappuccino",
    category: "coffee_and_tea",
    price: 2.8,
    description: null,
    size: null,
    special: false,
  },
  {
    name: "Latte Macchiato",
    category: "coffee_and_tea",
    price: 3.5,
    description: null,
    size: null,
    special: false,
  },
  {
    name: "Heiße Schokolade",
    category: "coffee_and_tea",
    price: 3.5,
    description: null,
    size: null,
    special: false,
  },
  {
    name: "Tee",
    category: "coffee_and_tea",
    price: 2.5,
    description: "Schwarz oder Minze",
    size: null,
    special: false,
  },
  {
    name: "Acqua Morelli",
    category: "beverages",
    price: 2.5,
    description: "medium oder still",
    size: "0,25l",
    special: false,
  },
  {
    name: "Acqua Morelli",
    category: "beverages",
    price: 5.5,
    description: "medium oder still",
    size: "0,75l",
    special: false,
  },
  {
    name: "Coca Cola, Fanta, Sprite, Coca Cola Zero, Spezi",
    category: "beverages",
    price: 2.5,
    description: null,
    size: "0,35l",
    special: false,
  },
  {
    name: "Coca Cola, Fanta, Sprite, Coca Cola Zero, Spezi",
    category: "beverages",
    price: 3.5,
    description: null,
    size: "0,45l",
    special: false,
  },
  {
    name: "Thomas Henry",
    category: "beverages",
    price: 2.5,
    description: "Tonic Water, Bitter Lemon, Ginger Ale oder Spicey Ginger",
    size: "0,20l",
    special: false,
  },
  {
    name: "Cucumis Limonade",
    category: "beverages",
    price: 3.5,
    description: "Gurke oder Lavendel",
    size: "0,33l",
    special: false,
  },
  {
    name: "Iced Café",
    category: "beverages",
    price: 3.5,
    description: null,
    size: "0,30l",
    special: false,
  },
  {
    name: "Apfel- oder Rhabarberschorle",
    category: "beverages",
    price: 2.5,
    description: null,
    size: "0,35l",
    special: false,
  },
  {
    name: "Apfel- oder Rhabarberschorle",
    category: "beverages",
    price: 3.5,
    description: null,
    size: "0,45l",
    special: false,
  },
  {
    name: "Hauswein, trocken",
    category: "red_wine",
    price: 4.5,
    description: "Cuvée, Frankreich",
    size: "0,20l",
    special: false,
  },
  {
    name: "Hauswein, trocken",
    category: "red_wine",
    price: 17,
    description: "Cuvée, Frankreich",
    size: "1l",
    special: false,
  },
  {
    name: "Primitivo, trocken",
    category: "red_wine",
    price: 5.5,
    description: "Feudi San Marzano, Italien",
    size: "0,20l",
    special: false,
  },
  {
    name: "Primitivo, trocken",
    category: "red_wine",
    price: 17,
    description: "Feudi San Marzano, Italien",
    size: "1l",
    special: false,
  },
  {
    name: "Tempranillo, trocken",
    category: "red_wine",
    price: 5.5,
    description: "Cal Y Canto, Spanien",
    size: "0,20l",
    special: false,
  },
  {
    name: "Tempranillo, trocken",
    category: "red_wine",
    price: 17,
    description: "Cal Y Canto, Spanien",
    size: "1l",
    special: false,
  },
  {
    name: "Shiraz, trocken",
    category: "red_wine",
    price: 25,
    description: "Koonunga Hill, Australien",
    size: "1l",
    special: false,
  },
  {
    name: "Black Print, trocken",
    category: "red_wine",
    price: 28,
    description: "Cuvée, Pfalz",
    size: "1l",
    special: false,
  },
  {
    name: "Rosé, trocken",
    category: "red_wine",
    price: 5.5,
    description: "Il Paso, Italien",
    size: "0.20l",
    special: false,
  },
  {
    name: "Rosé, trocken",
    category: "red_wine",
    price: 17,
    description: "Il Paso, Italien",
    size: "1l",
    special: false,
  },
  {
    name: "Prosecco, Hausmarke",
    category: "red_wine",
    price: 3.5,
    description: "asdsd",
    size: "0,10l",
    special: true,
  },

  {
    name: "Tartufo Eis",
    category: "dessert",
    price: 4.5,
    description: "hell oder dunkel",
    size: null,
    special: false,
  },
  {
    name: "Schokosoufflé",
    category: "dessert",
    price: 5.9,
    description: "mit Vanilleeis",
    size: null,
    special: false,
  },
  {
    name: "Nutella Pizza",
    category: "dessert",
    price: 6.9,
    description: "mit Vanilleeis",
    size: null,
    special: false,
  },
  {
    name: "König Pilsener",
    category: "beer_on_tap",
    price: 2.3,
    description: "Bier oder Alster",
    size: "0,25l",
    special: false,
  },
  {
    name: "König Pilsener",
    category: "beer_on_tap",
    price: 3.6,
    description: "Bier oder Alster",
    size: "0,40l",
    special: false,
  },
  {
    name: "Benediktiner Weissbie",
    category: "beer_on_tap",
    price: 2.8,
    description: null,
    size: "0,30l",
    special: false,
  },
  {
    name: "Benediktiner Weissbie",
    category: "beer_on_tap",
    price: 3.8,
    description: null,
    size: "0,50l",
    special: false,
  },
  {
    name: "König Pilsener",
    category: "beer_bottle",
    price: 2.6,
    description: "alkoholfrei",
    size: "0,33l",
    special: false,
  },
  {
    name: "Benediktiner Weissbier",
    category: "beer_bottle",
    price: 3.8,
    description: "alkoholfrei",
    size: "0,50l",
    special: false,
  },
  {
    name: "TH. KÖNIG Kellerbier",
    category: "beer_bottle",
    price: 3.5,
    description: null,
    size: "0,33l",
    special: false,
  },
  {
    name: "Hauswein, trocken",
    category: "white_wine",
    price: 4.5,
    description: "Cuvée, Frankreich",
    size: "0,20l",
    special: false,
  },
  {
    name: "Hauswein, trocken",
    category: "white_wine",
    price: 17,
    description: "Cuvée, Frankreich",
    size: "1l",
    special: false,
  },
  {
    name: "Werkstoff (Bio), halbtrocken",
    category: "white_wine",
    price: 5.5,
    description: "Sauvignon Blanc & Riesling, Rheinhessen",
    size: "0,20l",
    special: false,
  },
  {
    name: "Werkstoff (Bio), halbtrocken",
    category: "white_wine",
    price: 17,
    description: "Sauvignon Blanc & Riesling, Rheinhessen",
    size: "1l",
    special: false,
  },
  {
    name: "Riesling, trocken",
    category: "white_wine",
    price: 6.5,
    description: "Liebfrauenstift, Rheinhessen",
    size: "0,20l",
    special: false,
  },
  {
    name: "Riesling, trocken",
    category: "white_wine",
    price: 22,
    description: "Liebfrauenstift, Rheinhessen",
    size: "1l",
    special: false,
  },
  {
    name: "Grauburgunder, trocken",
    category: "white_wine",
    price: 6.9,
    description: "Bercher, Baden",
    size: "0,20l",
    special: false,
  },
  {
    name: "Grauburgunder, trocken",
    category: "white_wine",
    price: 24,
    description: "Bercher, Baden",
    size: "1l",
    special: false,
  },
  {
    name: "Riesling, trocken",
    category: "white_wine",
    price: 24,
    description: "Kallfelz, Mosel",
    size: "1l",
    special: false,
  },
]

export default menu
